VHDL_FILES = $(TOP_MODULE_FILE) \
../../../../rtl_emard/lattice/ulx3s/clocks/clk_25M_112M5_140Mp_140Mn_7M5.vhd \
../../../../rtl_emard/lattice/ulx3s/clocks/C64_Clock.vhd \
../../../../rtl_emard/lattice/ulx3s/clocks/DVI_PLL.vhd \
../../../../Minimig_ECS/impl1/source/Fampiga.vhd \
../../../../source_emard/cfide.vhd \
../../../../Minimig_ECS/impl1/source/Debounce.vhd \
../../../../Minimig_ECS/RTL/sdram_cache.vhd \
../../../../Minimig_ECS/impl1/source/TG68K.vhd \
../../../../Minimig_ECS/impl1/source/TG68K_ALU.vhd \
../../../../Minimig_ECS/impl1/source/TG68K_Pack.vhd \
../../../../Minimig_ECS/impl1/source/TG68KdotC_Kernel.vhd \
../../../../Minimig_ECS/impl1/source/HDMI/aux_ecc1.vhd \
../../../../Minimig_ECS/impl1/source/HDMI/aux_ecc2.vhd \
../../../../Minimig_ECS/impl1/source/HDMI/aux_encoder.vhd \
../../../../source_emard/HDMI/dvid.vhd \
../../../../Minimig_ECS/impl1/source/HDMI/dvienc_defs.vhd \
../../../../Minimig_ECS/impl1/source/HDMI/edvi_ucode.vhd \
../../../../Minimig_ECS/impl1/source/HDMI/infoframe_rom_800x600_60hz_40M_48k.vhd \
../../../../Minimig_ECS/impl1/source/HDMI/TMDS_encoder.vhd \
../../../../source_emard/poweronreset.vhd \
../../../../osd_bootstrap.vhd \
../../../../jbboot.vhd \
../../../../rtl_emard/generic/bram_true2p_1clk.vhd \
../../../../rtl_emard/vga/vga.vhd \
../../../../rtl_emard/vga/hdmi/vga2dvid.vhd \
../../../../rtl_emard/vga/hdmi/tmds_encoder.vhd \
../../../../rtl_emard/vga/lattice/ecp5u/ddr_out_emard.vhd \
../../../../rtl_emard/usbhid/usb_req_gen_func_pack.vhd \
../../../../rtl_emard/usbhid/usbhid_host.vhd \
../../../../rtl_emard/usbhid/usb_enum_saitek_minimal_pack.vhd \
../../../../rtl_emard/usbhid/usbhid_report_decoder_saitek.vhd \
../../../../rtl_emard/usbhid/report_decoded_pack_saitek.vhd \
../../../../rtl_emard/spdif/spdif_tx.vhd \
../../../../rtl_emard/osd/char_rom.vhd \
../../../../rtl_emard/generic/bram_true2p_1clk.vhd \
../../../../rtl_emard/vga/hdmi/tmds_encoder.vhd \
../../../../rtl_emard/vga/hdmi/ddr_dvid_out_se.vhd \

VERILOG_FILES = \
../../../../Minimig_ECS/impl1/source/Agnus.v \
../../../../Minimig_ECS/impl1/source/Amber.v \
../../../../Minimig_ECS/impl1/source/Audio.v \
../../../../Minimig_ECS/impl1/source/Beamcounter.v \
../../../../Minimig_ECS/impl1/source/Bitplanes.v \
../../../../Minimig_ECS/impl1/source/Blitter.v \
../../../../Minimig_ECS/impl1/source/CIA8520.v \
../../../../Minimig_ECS/impl1/source/Clock.v \
../../../../Minimig_ECS/impl1/source/Copper.v \
../../../../Minimig_ECS/impl1/source/Denise.v \
../../../../Minimig_ECS/impl1/source/Floppy.v \
../../../../Minimig_ECS/impl1/source/Gary.v \
../../../../Minimig_ECS/impl1/source/Gayle.v \
../../../../source_emard/Minimig1.v \
../../../../Minimig_ECS/impl1/source/Paula.v \
../../../../source_emard/PS2Keyboard.v \
../../../../source_emard/twowaycache.v \
../../../../Minimig_ECS/impl1/source/Sprites.v \
../../../../source_emard/Userio.v \
